version: '3.6'

services:
  web:
    build: .
    ports:
      - "4300:4300"
    depends_on:
      - fb-db
    command: ["/bin/main","/home/google-services.json"]
  fb-db:
    container_name: "firebase-db"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 021021ali
      MYSQL_DATABASE: firebase
      MYSQL_USER: aicam
      MYSQL_PASSWORD: 021021ali
    volumes:
      - "./mysql:/var/lib/mysql"
    expose:
      - 3306